---
Name: goldfinch-performance
---

---
Name: goldfinch-performance-icon
Only:
  moduleexists: "goldfinch/enchantment"
---
Goldfinch\Performance\Admin\PerformanceAdmin:
  menu_icon_class: "bi-speedometer"
